// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOp6DOozu_-QF3vMc2xEiBh2_rtTpy3PI',
    appId: '1:334747971586:android:a775d9d44b2a774317371b',
    messagingSenderId: '334747971586',
    projectId: 'myhighst-20471',
    databaseURL: 'https://myhighst-20471.firebaseio.com',
    storageBucket: 'myhighst-20471.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAruz1fq0j9gk8oYHveK0sR4_wYDjre9GE',
    appId: '1:334747971586:ios:afcb910a555a8d5c17371b',
    messagingSenderId: '334747971586',
    projectId: 'myhighst-20471',
    databaseURL: 'https://myhighst-20471.firebaseio.com',
    storageBucket: 'myhighst-20471.appspot.com',
    iosClientId: '334747971586-guj07f4fbm2n7ngv97fvfbvagbph6p1n.apps.googleusercontent.com',
    iosBundleId: 'com.example.myhighstMapApp',
  );
}
